#!/usr/bin/perl -w 
use strict;
use warnings;
BEGIN{
    push @INC, '/opt/local/lib/perl5/site_perl/5.12.4';
}
use ExtUtils::Installed;

my $inst = ExtUtils::Installed->new();
my @modules = $inst->modules();

foreach(@modules){
    my $ver = $inst->version($_) || "???";
    printf("%-12s----Version=>%s\n", $_, $ver);
}

exit 0;
